### ISSUE TITLE
ModuleNotFoundError: No module named 'pythagorean'

### ISSUE THREAD

**Issue by dvwright** [compuuteio/numerology#5]
Hi, I am experiencing import issues trying to use this package.

Steps to recreate:

```bash
$ pip install numerology
```
Collecting numerology
  Downloading numerology-1.0-py3-none-any.whl (35 kB)
Installing collected packages: numerology
Successfully installed numerology-1.0

```bash
$ python3 test.py
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from numerology import Pythagorean
  File "/home/dwright/Dev/python/pdev/lib/python3.9/site-packages/numerology/__init__.py", line 6, in <module>
    from pythagorean.common import Functions as fct
ModuleNotFoundError: No module named 'pythagorean'

#######
test.py
#######
from numerology import PythagoreanNumerology
his_numerology = PythagoreanNumerology("Barrack", "Obama", "1961-08-04")

**Comment by eguenou** [comment]
Merge done. Issue corrected.
Thank you!
